
CREATE DATABASE [MENDO_DW] 
    ON ( NAME = N'MENDO_DW', 
         FILENAME = N'F:\MENDO_DATA\MENDO_DW.mdf', 
         SIZE = 727425KB, MAXSIZE = UNLIMITED , FILEGROWTH = 1024KB )
    LOG ON ( NAME = N'MENDO_DW_log', 
         FILENAME = N'F:\MENDO_DATA\MENDO_DW_log.ldf', 
         SIZE = 1024KB, MAXSIZE = 1024000KB, FILEGROWTH = 10% )
    COLLATE Modern_Spanish_CI_AS
GO
